### ISSUE TITLE
flask admin initialize db throw UnicodeDecodeError : codec can't decode byte 0xae in position 129: illegal multibyte sequence

### ISSUE THREAD

**Issue by wakakaaaabbbb** [weijiang1994/Blogin#1]

**Comment by weijiang1994** [comment]
please confirm you database encode is utf8.

**Comment by weijiang1994** [comment]
因为在初始化数据库的时候在状态表中插入两个状态，使用中文命名的。代码如下
`Blogin/__init__.py`文件
```python
@app.cli.command()
    def admin():
        try:
            db.drop_all()
            db.create_all()
            Role.init_role()
            States.init_states()
# 省略后续代码
```

`/blogin/models.py`文件
```python
@staticmethod
    def init_states():
        s1 = States(name='正常')
        s2 = States(name='禁用')
        db.session.add(s1)
        db.session.add(s2)
        db.session.commit()
```
所以报这个错误应该是你数据库的编码没有设置为`utf8`。

**Comment by wakakaaaabbbb** [comment]
字符集没问题，我看看代码

**Comment by wakakaaaabbbb** [comment]
mysql> show variables like '%char%'
    -> ;
+--------------------------+----------------------------------------------+
| Variable_name            | Value                                        |
+--------------------------+----------------------------------------------+
| character_set_client     | utf8                                         |
| character_set_connection | utf8                                         |
| character_set_database   | utf8                                         |
| character_set_filesystem | binary                                       |
| character_set_results    | utf8                                         |
| character_set_server     | utf8                                         |
| character_set_system     | utf8                                         |
| character_sets_dir       | D:\mysql\mysql-8.0.20-winx64\share\charsets\ |
+--------------------------+----------------------------------------------+
8 rows in set, 1 warning (0.00 sec)

**Comment by weijiang1994** [comment]
```mysql
+--------------------------+----------------------------+
| Variable_name            | Value                      |
+--------------------------+----------------------------+
| character_set_client     | utf8                       |
| character_set_connection | utf8                       |
| character_set_database   | utf8                       |
| character_set_filesystem | binary                     |
| character_set_results    | utf8                       |
| character_set_server     | latin1                     |
| character_set_system     | utf8                       |
| character_sets_dir       | /usr/share/mysql/charsets/ |
+--------------------------+----------------------------+
```
这是我本地可用的数据库字符集

**Comment by weijiang1994** [comment]
问题解决了吗？
你可以手动插入中文数据到你的数据库试试，看看会不会报错。

**Comment by weijiang1994** [comment]
可能是你的 .env文件的编码不对 看你的报错还没到数据库那一步

**Comment by wakakaaaabbbb** [comment]
也不是env编码的问题，下班再看看hhh
