### ISSUE TITLE
这部分命令怎么使用呀

### ISSUE THREAD

**Issue by T485556595** [weijiang1994/Blogin#10]
![image](https://user-images.githubusercontent.com/84732966/129892375-167e05a7-37b7-4e85-8703-bb381116165e.png)

**Comment by T485556595** [comment]
研究半天不会使用

**Comment by T485556595** [comment]
研究半天不会使用

**Comment by weijiang1994** [comment]
你按照README.md里面的步骤，就知道怎么使用命令了。 https://github.com/weijiang1994/Blogin/blob/master/README.md

**Comment by T485556595** [comment]
![image](https://user-images.githubusercontent.com/84732966/129896623-a385a658-8da7-4b16-ae7d-bb888b17e746.png)

**Comment by T485556595** [comment]
执行命令会出错

**Comment by weijiang1994** [comment]
> 执行命令会出错

把你的项目目录截图看一下

**Comment by T485556595** [comment]
![image](https://user-images.githubusercontent.com/84732966/129897583-cf26d864-7c86-4436-9d98-6ceb324310bb.png)

**Comment by weijiang1994** [comment]
先运行`flask run`，然后关闭，在执行`flask initdb`试一下看看

**Comment by T485556595** [comment]
![image](https://user-images.githubusercontent.com/84732966/129900945-f66d594f-7679-4767-9082-9110f3b911ba.png)

**Comment by weijiang1994** [comment]
看看有没有python-dotenv包
