### ISSUE TITLE
插入数据问题

### ISSUE THREAD

**Issue by T485556595** [weijiang1994/Blogin#12]
我发现前台中每日一句板块中无法加载，研究了下源代码中发现根本未插入到数据库中，测试了下代码发现
![Snipaste_2021-08-25_16-58-32](https://user-images.githubusercontent.com/84732966/130761182-b6a3460b-5b45-400c-a2a1-9b718817b0e5.png)

**Comment by weijiang1994** [comment]
每日一句是通过定时任务自动插入的，你这样执行不再flask的上下文环境中，肯定会出错的。
每日一句的插入方式具体实现如下
https://github.com/weijiang1994/Blogin/blob/6e8b4df992380e8723a25eddaf78c38ba199e0c7/blogin/task.py#L30

**Comment by weijiang1994** [comment]
因为我的服务运行在服务器上面，服务每时每刻都会运行，因此不会出问题。你在本地测试的话，可以手动在数据库中插入几条数据进去，日期字段对上就好了。
