### ISSUE TITLE
   from flask_wtf.csrf import CSRFError ModuleNotFoundError: No module named 'flask_wtf'

### ISSUE THREAD

**Issue by tianke0711** [weijiang1994/Blogin#13]
你好
我安装了pip install  flask-wtf
但是还是有以上错误。
你好 能否弄一个简单的local运行步骤，在mac电脑上。

**Comment by weijiang1994** [comment]
> 你好 我安装了pip install flask-wtf 但是还是有以上错误。 你好 能否弄一个简单的local运行步骤，在mac电脑上。

确认一下是否安装在正确的环境中了？还有，我没有Mac电脑~:sweat:

**Comment by tianke0711** [comment]
flask run                 
 * Tip: There are .env or .flaskenv files present. Do "pip install python-dotenv" to use them.
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Usage: flask run [OPTIONS]

Error: While importing "wsgi", an ImportError was raised:

Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.8/site-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/Users/ketian/PycharmProjects/Blogin/wsgi.py", line 9, in <module>
    from blogin import create_app
  File "/Users/ketian/PycharmProjects/Blogin/blogin/__init__.py", line 13, in <module>
    from flask_wtf.csrf import CSRFError
ModuleNotFoundError: No module named 'flask_wtf'

(venv) (base) ketian@kes-MacBook-Pro Blogin %

**Comment by weijiang1994** [comment]
进入这个目录`/opt/anaconda3/lib/python3.8/site-packages/`看看有没有`flask_wtf`

**Comment by tianke0711** [comment]
@weijiang1994  现在OK啦 刚才我退出venv环境后再次activate后就OK啦 谢谢。 不过运行OK啦。
* Debug mode: on
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 303-652-989


但是还有其他问题。打开http://127.0.0.1:5000/ 后 出现啦

flask.cli.NoAppException
flask.cli.NoAppException: While importing "blogin", an ImportError was raised:

Traceback (most recent call last):
  File "/Users/ketian/PycharmProjects/Blogin/venv/lib/python3.8/site-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/Users/ketian/PycharmProjects/Blogin/blogin/__init__.py", line 15, in <module>
    from blogin.extension import db, bootstrap, moment, ckeditor, migrate, login_manager, share, avatar, mail, whooshee, \
  File "/Users/ketian/PycharmProjects/Blogin/blogin/extension.py", line 21, in <module>
    from flask_oauthlib.client import OAuth
ModuleNotFoundError: No module named 'flask_oauthlib'

**Comment by weijiang1994** [comment]
一般提示`No module named xxx`都是当前环境缺少对应的库，根据提示信息直接执行命令`pip install xxx`既可，方便的话点一下star吧，谢谢啦

**Comment by tianke0711** [comment]
@weijiang1994  谢谢 好的 已经star啦。好的

**Comment by tianke0711** [comment]
@weijiang1994 你好 你可以稍微解释一下 怎么部署在云服务器上以及相关ip设置等。这样会增加更多人的兴趣

**Comment by weijiang1994** [comment]
> @weijiang1994 好的 谢谢 肯定看的。建议你把这个博客源码，一步步开发的过程分享一下。比如从最简单的开始，到最后建成这个整体网站的过程中。分成好几篇来分享。感觉增加人气。

哈哈哈，这个我在考虑做，主要是写作教程不太擅长~ :cry:
