### ISSUE TITLE
configparser.NoSectionError: No section: 'baidu'

### ISSUE THREAD

**Issue by tianke0711** [weijiang1994/Blogin#14]
File "/Users/xx/PycharmProjects/Blogin/blogin/blueprint/front/blog.py", line 18, in <module>
    from blogin.utils import redirect_back, github_social, BOOTSTRAP_SUFFIX
  File "/Users/xx/PycharmProjects/Blogin/blogin/utils.py", line 281, in <module>
    OCR_TOKEN = config_ini.get('baidu', 'token')
  File "/opt/anaconda3/lib/python3.8/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/opt/anaconda3/lib/python3.8/configparser.py", line 1149, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'baidu'

**Comment by tianke0711** [comment]
TypeError: OAuthRemoteApp requires consumer key and secret

**Comment by weijiang1994** [comment]
> @weijiang1994 现在新建了 config.ini 我想问一下这个是啥 [baidu] ak = example-baidu-ak sk = example-baidu-sk token = example-baidu-token
> 
> ak sk token

这个是百度API要用的，你随便填也可以

**Comment by weijiang1994** [comment]
> TypeError: OAuthRemoteApp requires consumer key and secret
> 
> File "/Users/xx/PycharmProjects/Blogin/blogin/blueprint/front/oauth.py", line 29, in gitee = oauth.remote_app( File "/Users/xx/PycharmProjects/Blogin/venv/lib/python3.8/site-packages/flask_oauthlib/client.py", line 78, in remote_app remote = OAuthRemoteApp(self, name, **kwargs) File "/Users/xx/PycharmProjects/Blogin/venv/lib/python3.8/site-packages/flask_oauthlib/client.py", line 284, in **init** raise TypeError( TypeError: OAuthRemoteApp requires consumer key and secret

这个错误可以看这个 #2

**Comment by weijiang1994** [comment]
> @weijiang1994 OK！ 我想问一下你这个 ¥ SECRET_KEY='your project secret' 是啥 咋设置啊 随便设置一个密码吗

是的，随便设置一个就行了。

**Comment by tianke0711** [comment]
@weijiang1994  我设置了 咋还是这个问题啊

MAIL_SERVER='xx'
MAIL_USERNAME='xx'
MAIL_PASSWORD='xxx' # 不是你的邮箱密码,是申请的邮箱秘钥
SECRET_KEY='xx'
DATABASE_USER='root'
DATABASE_PWD='xxx'
# 百度翻译apiid 以及 key
BAIDU_TRANS_APPID='xx'
BAIDU_TRANS_KEY='xx'
# github第三方登录id以及key
GITHUB_CLIENT_ID='909d071895ae500cfdxx'
GITHUB_CLIENT_SECRET='56xxx'
# baidu ocr key
OCR_KEY='xxx'
OCR_SECRET='xx'
OCR_TOKEN='xxx'

**Comment by weijiang1994** [comment]
> @weijiang1994 我设置了 咋还是这个问题啊
> 
> MAIL_SERVER='xx' MAIL_USERNAME='xx' MAIL_PASSWORD='xxx' # 不是你的邮箱密码,是申请的邮箱秘钥 SECRET_KEY='xx' DATABASE_USER='root' DATABASE_PWD='xxx'
> 
> # 百度翻译apiid 以及 key
> BAIDU_TRANS_APPID='xx' BAIDU_TRANS_KEY='xx'
> 
> # github第三方登录id以及key
> GITHUB_CLIENT_ID='909d071895ae500cfdxx' GITHUB_CLIENT_SECRET='56xxx'
> 
> # baidu ocr key
> OCR_KEY='xxx' OCR_SECRET='xx' OCR_TO

> @weijiang1994 我设置了 咋还是这个问题啊
> 
> MAIL_SERVER='xx' MAIL_USERNAME='xx' MAIL_PASSWORD='xxx' # 不是你的邮箱密码,是申请的邮箱秘钥 SECRET_KEY='xx' DATABASE_USER='root' DATABASE_PWD='xxx'
> 
> # 百度翻译apiid 以及 key
> BAIDU_TRANS_APPID='xx' BAIDU_TRANS_KEY='xx'
> 
> # github第三方登录id以及key
> GITHUB_CLIENT_ID='909d071895ae500cfdxx' GITHUB_CLIENT_SECRET='56xxx'
> 
> # baidu ocr key
> OCR_KEY='xxx' OCR_SECRET='xx' OCR_TOKEN='xxx'

你按照我的readme.md步骤来

有些要在.env文件中设置 有些在config.ini文件中设置

**Comment by tianke0711** [comment]
127.0.0.1 - - [09/Oct/2021 21:22:44] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/ketian/PycharmProjects/Blogin/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/xx/PycharmProjects/Blogin/blogin/__init__.py", line 32, in <module>
    from blogin.blueprint.front.oauth import oauth_bp
  File "/Users/xx/PycharmProjects/Blogin/blogin/blueprint/front/oauth.py", line 29, in <module>
    gitee = oauth.remote_app(
  File "/Users/xx/PycharmProjects/Blogin/venv/lib/python3.8/site-packages/flask_oauthlib/client.py", line 78, in remote_app
    remote = OAuthRemoteApp(self, name, **kwargs)
  File "/Users/xx/PycharmProjects/Blogin/venv/lib/python3.8/site-packages/flask_oauthlib/client.py", line 284, in __init__
    raise TypeError(
TypeError: OAuthRemoteApp requires consumer key and secret

**Comment by tianke0711** [comment]
File "/Users/xx/PycharmProjects/Blogin/blogin/__init__.py", line 32, in <module>
from blogin.blueprint.front.oauth import oauth_bp
File "/Users/xx/PycharmProjects/Blogin/blogin/blueprint/front/oauth.py", line 17, in <module>
github = oauth.remote_app(
File "/Users/xx/PycharmProjects/Blogin/venv/lib/python3.8/site-packages/flask_oauthlib/client.py", line 80, in remote_app
assert name not in self.remote_apps
AssertionError

**Comment by tianke0711** [comment]
File "/Users/xx/PycharmProjects/Blogin/venv/lib/python3.8/site-packages/flask_oauthlib/client.py", line 80, in remote_app
 
        Find more parameters from :class:`OAuthRemoteApp`.
        """
        remote = OAuthRemoteApp(self, name, **kwargs)
        if register:
            assert name not in self.remote_apps
            self.remote_apps[name] = remote
        return remote
 
    def __getattr__(self, key):
        try:

**Comment by tianke0711** [comment]
这个是啥 
GITEE_CLIENT_ID='gitee cid'
GITEE_CLIENT_SECRET='gitee secret'

**Comment by weijiang1994** [comment]
gitee第三方登录相关的配置

**Comment by weijiang1994** [comment]
> 我没有用这个不需要输入吧

配置一下就行了在.env中，随便设置值

**Comment by weijiang1994** [comment]
> @weijiang1994 初始化OK啦。 首页显示OK。但是点击登录后出现了错误。还有超级管理员从哪登录啊
> 
> File "/Users/xx/PycharmProjects/Blogin/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request return self.view_functions[rule.endpoint](**req.view_args) File "/Users/xx/PycharmProjects/Blogin/blogin/blueprint/front/auth.py", line 54, in login ban_ip = rd.get(str(remote_ip)) File "/Users/xx/PycharmProjects/Blogin/venv/lib/python3.8/site-packages/redis/client.py", line 1606, in get return self.execute_command('GET', name) File "/Users/xx/PycharmProjects/Blogin/venv/lib/python3.8/site-packages/redis/client.py", line 898, in execute_command conn = self.connection or pool.get_connection(command_name, **options) File "/Users/xx/PycharmProjects/Blogin/venv/lib/python3.8/site-packages/redis/connection.py", line 1192, in get_connection connection.connect() File "/Users/xx/PycharmProjects/Blogin/venv/lib/python3.8/site-packages/redis/connection.py", line 563, in connect raise ConnectionError(self._error_message(e)) redis.exceptions.ConnectionError: Error 61 connecting to localhost:6379. Connection refused.

超级管理员通过执行`flask admin`创建，后面的错误是你需要安装一个redis数据库

**Comment by tianke0711** [comment]
@weijiang1994  安装好了。我管理员登录后 咋能写博客啊 我没看到哪个页面是写博客的？

**Comment by weijiang1994** [comment]
> @weijiang1994 安装好了。我管理员登录后 咋能写博客啊 我没看到哪个页面是写博客的？

你执行`flask admin`命令的时候创建的账号就是管理员，用它登录，然后点击右上角，后台管理就可以进入后台页面了。

**Comment by weijiang1994** [comment]
看看你数据库`role`表的数据

**Comment by tianke0711** [comment]
+----+-------+------------+
| id | name  | permission |
+----+-------+------------+
|  1 | ADMIN | ANY        |
|  2 | USER  | SOME       |

**Comment by weijiang1994** [comment]
那怎么会看不到呢 不应该啊 看看你账号的数据库信息

**Comment by tianke0711** [comment]
@weijiang1994  我刚看了user 信息 role id 咋变成啦2 啦 2 是user啊
<img width="419" alt="截屏2021-10-09 23 42 21" src="https://user-images.githubusercontent.com/6407418/136662677-aef716d6-02bf-4b33-bbd7-840c052773b0.png">

**Comment by weijiang1994** [comment]
> @weijiang1994 我刚看了user 信息 role id 咋变成啦2 啦 2 是user啊 <img alt="截屏2021-10-09 23 42 21" width="419" src="https://user-images.githubusercontent.com/6407418/136662677-aef716d6-02bf-4b33-bbd7-840c052773b0.png">

flask admin赋值的是1的，你数据库手动改一下吧

**Comment by tianke0711** [comment]
@weijiang1994  改好就OK啦，就可以看到后台编辑界面啦。 奇怪为啥flask admin搞错了呢。你可以测试一下为啥。
今天谢谢你的指导。明天我再仔细看看。

**Comment by weijiang1994** [comment]
> @weijiang1994 改好就OK啦，就可以看到后台编辑界面啦。 奇怪为啥flask admin搞错了呢。你可以测试一下为啥。 今天谢谢你的指导。明天我再仔细看看。

👍

**Comment by tianke0711** [comment]
@weijiang1994  你好 我写博客的时候 界面无法选择博客类型。说有错误 Not a valid choice

/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/xx/PycharmProjects/Blogin/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/xx/PycharmProjects/Blogin/venv/lib/python3.8/site-packages/flask_caching/__init__.py", line 475, in decorated_function
    rv = f(*args, **kwargs)
  File "/Users/xx/PycharmProjects/Blogin/blogin/blueprint/front/blog.py", line 308, in load_one
    return jsonify({'one': one.content})
AttributeError: 'NoneType' object has no attribute 'content'

**Comment by weijiang1994** [comment]
你要现在后台创建一个博客类型呀
![image](https://user-images.githubusercontent.com/53400477/136681877-9dbd5356-d16e-47c9-9811-571f48f8c1e4.png)

**Comment by tianke0711** [comment]
@weijiang1994  好的 谢谢 OK啦
