### ISSUE TITLE
 使用NGINX、GUNICORN部署项目在云服务器

### ISSUE THREAD

**Issue by tianke0711** [weijiang1994/Blogin#19]
我在看你的博客:https://2dogz.cn/blog/article/2/
我看你是在/etc/nginx/sites-available/里配置文件。
我以前部署在aws ec2 是在 /etc/nginx/sites-enabled/建的配置文件文件 我想问一下有啥区别。

**Comment by tianke0711** [comment]
你意思是process log？这个在哪里process log？

**Comment by weijiang1994** [comment]
一般在`/var/log/supervisor`目录

**Comment by tianke0711** [comment]
@weijiang1994  我加了一个startsecs=0  在blog.conf文件中。
虽然可以:RUNNING   pid 7138, uptime 0:00:00
但是我发现网页打不开。
502 Bad Gateway
nginx/1.14.0 (Ubuntu)

**Comment by weijiang1994** [comment]
502说明你NGINX反向代理没有配置正确

**Comment by tianke0711** [comment]
@weijiang1994 我开始只用gunicorn -w 4 wsgi:app 网页可以打开啊

**Comment by weijiang1994** [comment]
不清楚你怎么配置的，我也搞不清楚原因。

**Comment by tianke0711** [comment]
@weijiang1994  为啥大家使用不同呢
https://blog.csdn.net/guolindonggld/article/details/83386920

**Comment by tianke0711** [comment]
@weijiang1994 我感觉是不是安装问题， 为啥是python2版本的supervisor
sudo apt-get install supervisor
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libpython-stdlib libpython2.7-minimal libpython2.7-stdlib python python-meld3 python-minimal python-pkg-resources python2.7 python2.7-minimal
Suggested packages:
  python-doc python-tk python-setuptools python2.7-doc binfmt-support supervisor-doc
The following NEW packages will be installed:
  libpython-stdlib libpython2.7-minimal libpython2.7-stdlib python python-meld3 python-minimal python-pkg-resources python2.7 python2.7-minimal supervisor
0 upgraded, 10 newly installed, 0 to remove and 36 not upgraded.
Need to get 0 B/4382 kB of archives.

**Comment by weijiang1994** [comment]
不是很清楚，我的ubuntu1604没有问题

**Comment by tianke0711** [comment]
@weijiang1994 你好 commnd加上了/usr/bin/python3 /home/ubuntu/.local/bin/gunicorn -w 4 wsgi:app supervisor OK啦 还有user改成ubuntu 成功了。
但是我发现我无法域名访问，只能用ip地址访问。很奇怪。我记得当时只是单纯在terminal运行gunicorn -w 4 wsgi:app 时候域名可以访问。

**Comment by tianke0711** [comment]
我今天写博客时候 点击提交后出现了这个问题:
/10/31 00:59:28 [error] 10234#10234: *1338 client intended to send too large body: 1539034 bytes,

**Comment by weijiang1994** [comment]
Nginx中设置的最大文件大小过小

**Comment by tianke0711** [comment]
@weijiang1994  哪个文件 这个吗do vim /etc/nginx/sites-available/default？

**Comment by weijiang1994** [comment]
自己搜一下

**Comment by tianke0711** [comment]
@weijiang1994  OK啦 修改完。加了client_max_body_size 1024M; 在/etc/nginx/nginx.conf里。
还有我上传我手机以前拍摄的照片为啥不可以啊 说直接受jpd和png图片。但是我选择实时拍摄，然后上传照片就可以。

**Comment by tianke0711** [comment]
@weijiang1994  我修改以前的博客，但是点击提交后出现了错误
FileNotFoundError: [Errno 2] No such file or directory: '/Users/xx/PycharmProjects/Blogin/history/41590fc30458a88c584b7c8dedfa5749.txt'

**Comment by weijiang1994** [comment]
这种错误你应该知道怎么解决吧？

**Comment by tianke0711** [comment]
@weijiang1994  我加了history文件夹。

**Comment by tianke0711** [comment]
@weijiang1994  你是不是登录我的后台啦

**Comment by weijiang1994** [comment]
> @weijiang1994 你是不是登录我的后台啦

我没登录啊，我只是注册了账号而已...

**Comment by tianke0711** [comment]
@weijiang1994 好的 我得修改一下代码。我看你超级管理员

**Comment by weijiang1994** [comment]
你可以改一下代码，因为我当初把通过我的邮箱注册账号自动设置为超级管理员

**Comment by tianke0711** [comment]
@weijiang1994  好的

**Comment by tianke0711** [comment]
@weijiang1994  到此为止，谢谢你的指导。我后面会对网站进行修改一下 增加一些我的特色。不过暂时只是写写博客，时间有限。
