### ISSUE TITLE
TypeError: OAuthRemoteApp requires consumer key and secret

### ISSUE THREAD

**Issue by BravoLu** [weijiang1994/Blogin#2]
作者你好， 我想知道这个bug是因为.env文件的字段没有写完整吗 
TypeError: OAuthRemoteApp requires consumer key and secret
另外 
flask admin 
好像并没有这个指令，没怎么用过flask， 望指教。

**Comment by weijiang1994** [comment]
> 作者你好， 我想知道这个bug是因为.env文件的字段没有写完整吗
> TypeError: OAuthRemoteApp requires consumer key and secret
> 另外
> flask admin
> 好像并没有这个指令，没怎么用过flask， 望指教。


第一个错误是因为你的.env文件中没有加入github第三方登录的配置，你需要到github申请，然后填入到.env文件如下key中，[申请连接](https://github.com/settings/developers )。
```ini
# github第三方登录id以及key
GITHUB_CLIENT_ID='your github client id'
GITHUB_CLIENT_SECRET='your github client secret'
```
第二个错误找不到`flask admin` 命令是因为该命令依赖 `cli`库，你需要在根目录中执行 `pip install -r requirments.txt` 命令。

**Comment by BravoLu** [comment]
> 另外

添加了github第三方登录的client ID/client secret依然出现这个错误。

**Comment by Jowitt419** [comment]
我按照你的连接，去github申请了 client_id 和 client_secret 写入了.env中，但是依旧报这个错误。


DATABASE_USER= root# 设置你自己的数据库连接用户名
DATABASE_PWD= 123456# 设置你自己的数据库连接用户登录密码
DATABASE_HOST=127.0.0.1
DATABASE_PORT=3306
SECRET_KEY='dev'
MAIL_SERVER='smtp.qq.com'
MAIL_USERNAME= ''# 设置邮箱名
MAIL_PASSWORD= ''# 设置邮箱秘钥,不是登录密码而是申请SMTP时自动生成的秘钥
GITHUB_CLIENT_ID= 'bebf99be3c6f62cd662c'# (Github)第三方登录标识 
GITHUB_CLIENT_SECRET= 'bf79b6a6e71050aaaff486a82e7c01fe6ec786b8'# (Github)第三方登录密钥
GITEE_CLIENT_ID=   ‘’# (Gitee)第三方登录标识
GITEE_CLIENT_SECRET=   ‘’# (Gitee)第三方登录密钥
OSCHINA_CLIENT_ID=‘’
OSCHINA_CLIENT_SECRET=‘’

**Comment by natsume37** [comment]
一样呀 我也是、添加了gethub文件后也还是报这个错误，

> 我按照你的连接，去github申请了client_id和client_secret写入了.env中，但是仍然报这个错误。
> 
> DATABASE_USER= root# 设置你自己的数据库连接用户名 DATABASE_PWD= 123456# 设置你自己的数据库连接用户登录密码 DATABASE_HOST=127.0.0.1 DATABASE_PORT=3306 SECRET_KEY='dev' MAIL_SERVER='smtp.qq.com' MAIL_USERNAME= ' '# 设置邮箱名 MAIL_PASSWORD= ''# 设置邮箱秘钥,不是登录密码而是申请SMTP时自动生成的秘钥GITHUB_CLIENT_ID = 'bebf99be3c6f62cd662c'# (Github)第三方登录标志GITHUB_CLIENT_SECRET= ' bf79b6a6e71050aaaff486a82e7c01fe6ec786b8' #（Github）第三方登录键 GITEE_CLIENT_ID= ''# (Gitee)第三方登录标识 GITEE_CLIENT_SECRET= ''# (Gitee)第三方登录键 OSCHINA_CLIENT_ID='' OSCHINA_CLIENT_SECRET=''

**Comment by natsume37** [comment]
> 我按照你的连接，去github申请了client_id和client_secret写入了.env中，但是仍然报这个错误。
> 
> DATABASE_USER= root# 设置你自己的数据库连接用户名 DATABASE_PWD= 123456# 设置你自己的数据库连接用户登录密码 DATABASE_HOST=127.0.0.1 DATABASE_PORT=3306 SECRET_KEY='dev' MAIL_SERVER='smtp.qq.com' MAIL_USERNAME= ' '# 设置邮箱名 MAIL_PASSWORD= ''# 设置邮箱秘钥,不是登录密码而是申请SMTP时自动生成的秘钥GITHUB_CLIENT_ID = 'bebf99be3c6f62cd662c'# (Github)第三方登录标志GITHUB_CLIENT_SECRET= ' bf79b6a6e71050aaaff486a82e7c01fe6ec786b8' #（Github）第三方登录键 GITEE_CLIENT_ID= ''# (Gitee)第三方登录标识 GITEE_CLIENT_SECRET= ''# (Gitee)第三方登录键 OSCHINA_CLIENT_ID='' OSCHINA_CLIENT_SECRET=''

问题已解决、又试了好多次、可以了。
