### ISSUE TITLE
在腾讯云的轻量应用服务器 Ubuntu Server 20.04 LTS 64bit 镜像无法正常安装 Python 依赖

### ISSUE THREAD

**Issue by MIracleyin** [weijiang1994/Blogin#20]
希望可以给出一个 Docker 镜像打包这个 venv 环境，或者更新一下新的依赖版本～

**Comment by weijiang1994** [comment]
> 希望可以给出一个 Docker 镜像打包这个 venv 环境，或者更新一下新的依赖版本～

不会吧，我的就是部署在腾讯云轻量服务器2004上的啊？哪个依赖不能安装呀？

**Comment by MIracleyin** [comment]
这样吗
一开始是 matplotlib 安装出现问题，我升级了一下 venv pip 的版本，然后把 matlablib 版本设置成 大于等于 3.0.3 过了

但最后依赖安装完之后，报了一个 .h 库不存在

**Comment by weijiang1994** [comment]
![image](https://user-images.githubusercontent.com/53400477/148086266-eae1447f-59f1-411a-8cbd-911c3c0a1bd1.png)

**Comment by weijiang1994** [comment]
> 这样吗 一开始是 matplotlib 安装出现问题，我升级了一下 venv pip 的版本，然后把 matlablib 版本设置成 大于等于 3.0.3 过了
> 
> 但最后依赖安装完之后，报了一个 .h 库不存在

那你可以把matplotlib库注释掉吗，这个库没有必要，当初跑了一个demo，忘记删掉了

**Comment by MIracleyin** [comment]
![image](https://user-images.githubusercontent.com/29721742/148086915-900078bc-da9c-4ca9-a7f2-c59cc23cc5de.png)
环境是和你一样的，目前 matplotlib 注释掉了
目前卡在 psutil， 然后我把 psutil 的版本设置成 >= 现在过了

**Comment by MIracleyin** [comment]
目前环境问题都过了，明天继续试试看，还有一个问题，如果 .env 想暂时测试，准备什么内容都不填会报错，请问有什么方便测试的方案呢

**Comment by MIracleyin** [comment]
很棒的项目～ 期待后续更新

**Comment by weijiang1994** [comment]
> 目前环境问题都过了，明天继续试试看，还有一个问题，如果 .env 想暂时测试，准备什么内容都不填会报错，请问有什么方便测试的方案呢

.env文件中，除了`数据库配置`以及`secret`配置外，其他的可以不用填写。

**Comment by weijiang1994** [comment]
> 很棒的项目～ 期待后续更新

好的，谢谢 :smile:
