### ISSUE TITLE
在本地调试初始化数据库的时候报错

### ISSUE THREAD

**Issue by kevin-hwk** [weijiang1994/Blogin#21]
D:\Blogin>flask initdb
Error: While importing 'blogin', an ImportError was raised.

Usage: flask [OPTIONS] COMMAND [ARGS]...
Try 'flask --help' for help.

Error: No such command 'initdb'.
是循环导入了吗？

**Comment by kevin-hwk** [comment]
又尝试了几次，最后发现应该是 python-dotenv的版本问题，默认装的0.14.0会在数据库初始化的时候报编码问题，我重新把他卸载后装0.19.2，就能初始化成功了。真魔性，感谢你的热心解答

**Comment by weijiang1994** [comment]
> 又尝试了几次，最后发现应该是 python-dotenv的版本问题，默认装的0.14.0会在数据库初始化的时候报编码问题，我重新把他卸载后装0.19.2，就能初始化成功了。真魔性，感谢你的热心解答

不客气，编码错误可以把.env中的中文删掉。
