### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by tianke0711** [weijiang1994/Blogin#23]
你好， 网站出现了Internal Server Error，博客都无法展示 ，但是一般页面可以展示，但是博客内容以及其他的内容无法展示。这一般啥问题

**Comment by weijiang1994** [comment]
> 你好， 网站出现了Internal Server Error，博客都无法展示 ，但是一般页面可以展示，但是博客内容以及其他的内容无法展示。这一般啥问题

一般是代码运行出错了，具体原因要看后台日志。

**Comment by tianke0711** [comment]
我看了/log文件都是
blogin.log  blogin.log.1  blogin.log.2  blogin.log.3  task.log  task.log.1  task.log.10  task.log.2  task.log.3  task.log.4  task.log.5  task.log.6  task.log.7  task.log.8  task.log.9
看哪一个呢很多都是

021-12-09 07:19:27,953 INFO 更新github仓库信息成功!
2021-12-09 07:20:23,530 INFO 异常流量检测成功，检测时刻:2021-12-09 07:20:23.530563，检测时间段:['2021:07:19', '2021:07:20']，检测详情:{}
2021-12-09 07:21:23,530 INFO 异常流量检测成功，检测时刻:2021-12-09 07:21:23.530311，检测时间段:['2021:07:20', '2021:07:21']，检测详情:{}
2021-12-09 07:22:23,530 INFO 异常流量检测成功，检测时刻:2021-12-09 07:22:23.530377，检测时间段:['2021:07:21', '2021:07:22']，检测详情:{'45.155.205.233': 1}
2021-12-09 07:23:23,530 INFO 异常流量检测成功，检测时刻:2021-12-09 07:23:23.530380，检测时间段:['2021:07:22', '2021:07:23']，检测详情:{

**Comment by weijiang1994** [comment]
不知道你是怎么部署的，先看一下`blogin.log`

**Comment by tianke0711** [comment]
blogin.log.3

 File "/home/ubuntu/.local/lib/python3.6/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1698, "Access denied for user 'root'@'localhost'")

The above exception was the direct cause of the following exception:

**Comment by weijiang1994** [comment]
> 

数据库连接错误，你在`.env`文件配置的数据库连接有问题。

**Comment by tianke0711** [comment]
我前面没问题啊 我最近也一直没改啊 难道密码被人改了

**Comment by tianke0711** [comment]
是不是访问数据库看看 是否能正常登录

**Comment by tianke0711** [comment]
确实 密码忘了 不是我设置的密码，这可咋弄，需要重新设置把。

**Comment by weijiang1994** [comment]
你能登录MySQL吗？

**Comment by tianke0711** [comment]
> 你能登录MySQL吗？

无法登录，密码不是我设置default

**Comment by tianke0711** [comment]
我重新设置看看

**Comment by weijiang1994** [comment]
解决了吗？我关闭issue了

**Comment by tianke0711** [comment]
@weijiang1994 没解决 为啥我sudo mysql -u root可以进去，然后改了root密码。但是为啥 mysql -u root -p输入密码不行啊

**Comment by weijiang1994** [comment]
> @weijiang1994 没解决 为啥我sudo mysql -u root可以进去，然后改了root密码。但是为啥 mysql -u root -p输入密码不行啊

那你重新创建一个MySQL用户就行了 参考我这篇文章https://2dogz.cn/blog/article/30/

**Comment by tianke0711** [comment]
@weijiang1994 我重新新建了一个用户，然后在.env修改啦。咋还是network error错误啊。需要重新启动程序吧

**Comment by weijiang1994** [comment]
重启一下程序

**Comment by tianke0711** [comment]
谢谢 OK啦。很多都忘了 看来我需要记录下来的一些处理错误。 我最近会重新对网站进行改造，到时候还要像你请教。

**Comment by weijiang1994** [comment]
@tianke0711 建议定时备份数据库数据，防止数据丢失~

**Comment by tianke0711** [comment]
@weijiang1994  谢谢建议 怎么备份数据库数据啊， 你可有博客介绍啊

**Comment by weijiang1994** [comment]
先创建一个shell脚本，把下面{}里的内容替换成自己实际的信息
```shell
#!/bin/bash
date_str=$(date "+%Y-%m-%d")
echo $date_str
cd {你想存放的路径}
mysqldump -h 127.0.0.1 -u {数据库用户} --password={数据库密码} -R -E -e \{数据库名称}> {你想存放的路径}/$date_str.sql
tar -Jcvf $date_str.tar.xz $date_str.sql
rm $date_str.sql
```
然后通过crontab设置定时任务，具体设置方法自行百度。
