### ISSUE TITLE
数据库死锁

### ISSUE THREAD

**Issue by 199206155416** [weijiang1994/Blogin#25]
(pymysql.err.OperationalError) (1205, 'Lock wait timeout exceeded; try restarting transaction')
![image](https://user-images.githubusercontent.com/19886365/161030210-541b2930-3837-4ba1-b102-be469631a26b.png)

**Comment by weijiang1994** [comment]
哪段代码？

**Comment by 199206155416** [comment]
好像是阅读次数修改的时候，两个用户同时看，就会死锁；










在 2022-03-31 18:04:25，"weijiang1994" ***@***.***> 写道：

哪段代码？

**Comment by 199206155416** [comment]
> 哪段代码？

好像是阅读次数修改的时候，两个用户同时看，就会死锁；
![image](https://user-images.githubusercontent.com/19886365/161034328-b8eaa4bb-116a-4b9d-bd14-102762b0340a.png)

**Comment by weijiang1994** [comment]
你把`db.session.commit()`放到`blog.read_times += 1`下面去试试看。
