### ISSUE TITLE
我打算开发一个活动栏目。

### ISSUE THREAD

**Issue by tianke0711** [weijiang1994/Blogin#27]
我打算开发一个活动栏目。比如有啥足球活动，我想大家可以报名参加，有活动标题以及信息，活动内容，时间，地点，以及报名按钮。可有啥建议咋设计这个？如果有相关模版就好了。

**Comment by weijiang1994** [comment]
就是一个表单的事情，自己设计一下数据表，没有什么难度。

**Comment by tianke0711** [comment]
@weijiang1994  好的 我先设计一下 不懂再问你
