### ISSUE TITLE
其它操作系统

### ISSUE THREAD

**Issue by 99memory** [weijiang1994/Blogin#29]
**博主可以出一个centos7的安装教程嘛？**

**Comment by weijiang1994** [comment]
跟ubuntu大同小异吧，没太大区别呀~

**Comment by 99memory** [comment]
我在centos7里面试了几遍了，都不太行。那俺再研究下&nbsp;


stdy
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月19日(星期二) 下午5:53
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [weijiang1994/Blogin] 其它操作系统 (Issue #29)





 
@99memory 跟ubuntu大同小异吧，没太大区别呀~

**Comment by 99memory** [comment]
好滴，好滴。我现在把之前系统重装了一遍试试,有问题可以再接着请教嘛？&nbsp;


stdy
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月20日(星期三) 晚上8:50
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [weijiang1994/Blogin] 其它操作系统 (Issue #29)





 
@99memory 可以贴一下错误详情

**Comment by weijiang1994** [comment]
@99memory 可以的

**Comment by 99memory** [comment]
这里显示导入这个redis找不到我在网上搜索了两种方法都导入成功了，但是还是会显示这个
(16条消息) PYTHON——ImportError: No module named redis_reidlv的博客-CSDN博客
这个是教程
还有上面的报错：
While importing "wsgi", an ImportError was raised
我看网上说是：存在循环引入，可是我确实没发现在哪里有这个问题
就可以请教下吗？
谢谢


&nbsp;


stdy
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月20日(星期三) 晚上9:09
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [weijiang1994/Blogin] 其它操作系统 (Issue #29)





 
@99memory 可以的

**Comment by weijiang1994** [comment]
@99memory 你到github上回复吧，你邮件回复的看不清楚。

**Comment by weijiang1994** [comment]
@99memory 应该不是循环导入错误，应该是有些包没有安装。

**Comment by 99memory** [comment]
#Q1error: **command 'gcc' failed with exit status 1**

`psutil/_psutil_common.c:9:20: fatal error: Python.h: No such file or directory
     #include <Python.h>
                        ^
    compilation terminated.
    error: command 'gcc' failed with exit status 1
`

#Q2 Error: No such command 'initdb'.
` * Tip: There are .env or .flaskenv files present. Do "pip install python-dotenv" to use them.
Usage: flask [OPTIONS] COMMAND [ARGS]...
Try 'flask --help' for help.

Error: No such command 'initdb'.
 * Tip: There are .env or .flaskenv files present. Do "pip install python-dotenv" to use them.
Usage: flask [OPTIONS] COMMAND [ARGS]...
Try 'flask --help' for help.`

#Q3Error: No such command 'admin'.

`* Tip: There are .env or .flaskenv files present. Do "pip install python-dotenv" to use them.
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Usage: flask run [OPTIONS]`

#Q4 Error: While importing "wsgi", an ImportError was raised:
`Traceback (most recent call last):
  File "/www/wwwroot/Blogin-master/venv/lib64/python3.6/site-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/www/wwwroot/Blogin-master/wsgi.py", line 8, in <module>
    from blogin import create_app
  File "/www/wwwroot/Blogin-master/blogin/__init__.py", line 14, in <module>
    from blogin.extension import db, bootstrap, moment, ckeditor, migrate, login_manager, share, avatar, mail, whooshee, \
  File "/www/wwwroot/Blogin-master/blogin/extension.py", line 22, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'`

![question](https://user-images.githubusercontent.com/102737052/180102221-97189e2f-ab0b-4212-a8f0-d5b50bebed72.jpg)
这是报错的模块

**Comment by weijiang1994** [comment]
@99memory pip install redis python-dotenv

**Comment by 99memory** [comment]
> 
这个我安装后还是会出现一样的错误，然后又根据网上查阅的资料：
提示使用
`yum install python-devel.x86_64`
和
`pip install psutil`
来进行安装
之后仍然是上面的错误
这是使用yum install python-devel的问题
![question](https://user-images.githubusercontent.com/102737052/180137738-06c5eefb-f665-4aa8-b90d-0d309d857a8e.jpg)

以下是之前更加详细的问题截图：
![question1](https://user-images.githubusercontent.com/102737052/180137867-fa58f639-735f-4d00-898c-1868d6003281.jpg)

![question2](https://user-images.githubusercontent.com/102737052/180137938-3ce43020-406a-4625-9910-7f1f829e14d9.jpg)

![question3](https://user-images.githubusercontent.com/102737052/180137890-0cb6f1d1-6a1f-453f-89ce-c640937f14b9.jpg)

![question4](https://user-images.githubusercontent.com/102737052/180137899-49993c25-9e19-4ee0-a442-41030429c08a.jpg)

**Comment by weijiang1994** [comment]
@99memory yum install python3-devel,需要安装Python3的，这博客系统是依赖Python3。

**Comment by 99memory** [comment]
不过显然这个host和port是打不开的，并不能运行。所以就想看看是不是我的端口号和地址错了

**Comment by weijiang1994** [comment]
@99memory 你这样肯定无法访问的，第一，127是本地地址要用0.0.0.0去启动才可以访问，只能服务器本地访问，第二，5000端口应该是被防火墙禁用了，需要开启，同时在安全策略上配置一下5000端口的出入找规则。

**Comment by 99memory** [comment]
![image](https://user-images.githubusercontent.com/102737052/180215819-5c88c8c4-363d-4fb2-9ee3-cb55de8bdc05.png)
5000端口在腾讯云还有宝塔面板5000端口都已开放
![image](https://user-images.githubusercontent.com/102737052/180216275-750458dc-74ba-44c8-aa24-6e3bff8769fc.png)
我参照之前部署的一个flask项目的过程部署的，有些还不太明白，当时项目是通过：
` app.run(host="0.0.0.0",port=8090)`
的方式指定端口号和地址的。
博主这个博客系统比较复杂，有些地方我还没有看懂，这个是
端口和0.0.0.0的指定是在我前面提到的这个里面吗？
![image](https://user-images.githubusercontent.com/102737052/180217036-b631fc17-1bb4-4095-8662-58e273af2d1e.png)

**Comment by weijiang1994** [comment]
> ![image](https://user-images.githubusercontent.com/102737052/180215819-5c88c8c4-363d-4fb2-9ee3-cb55de8bdc05.png) 5000端口在腾讯云还有宝塔面板5000端口都已开放 ![image](https://user-images.githubusercontent.com/102737052/180216275-750458dc-74ba-44c8-aa24-6e3bff8769fc.png) 我参照之前部署的一个flask项目的过程部署的，有些还不太明白，当时项目是通过： ` app.run(host="0.0.0.0",port=8090)` 的方式指定端口号和地址的。 博主这个博客系统比较复杂，有些地方我还没有看懂，这个是 端口和0.0.0.0的指定是在我前面提到的这个里面吗？ ![image](https://user-images.githubusercontent.com/102737052/180217036-b631fc17-1bb4-4095-8662-58e273af2d1e.png)

你是怎么运行的？直接flask run --host 0.0.0.0 就可以了

**Comment by 99memory** [comment]
我这个本地的话是在pycharm上开发的flask项目，它里面有flask的运行配置。不是通过命令行运行的。
腾讯云服务器中的项目是通过集成工具：**python项目管理器**进行部署的。

**Comment by weijiang1994** [comment]
> 我这个本地的话是在pycharm上开发的flask项目，它里面有flask的运行配置。不是通过命令行运行的。 腾讯云服务器中的项目是通过集成工具：**python项目管理器**进行部署的。

没用过宝塔不太清楚怎么修改😂

**Comment by 99memory** [comment]
> 

好滴，谢谢博主啦。我再研究一下。
![image](https://user-images.githubusercontent.com/102737052/180220937-90109e6f-35cb-4018-9172-46be1c40da77.png)
