### ISSUE TITLE
jinja2.exceptions.TemplateNotFound: main/index.html

### ISSUE THREAD

**Issue by sci2sci** [weijiang1994/Blogin#30]
我把根文件名改成scisci后，然后flask run 后是这个问题

jinja2.exceptions.TemplateNotFound: main/index.html

```
`File "/Users/xx/PycharmProjects/SciSci/scisci/blueprint/front/blog.py", line 45, in index
    plans = Plan.query.filter_by(is_done=0).all()
    su = User.query.filter(User.email == 'sciscipaper@gmail.com').first()
    flinks = FriendLink.query.filter(FriendLink.flag == 1).all()
    msg_borders = MessageBorder.query.filter(MessageBorder.flag == 0, MessageBorder.parent_id == 0
                                             ).order_by(MessageBorder.timestamps.desc()).all()[0:5]
    return render_template('main/index.html', per_page=current_app.config['BLOGIN_BLOG_PER_PAGE'],
                           pagination=pagination, blogs=blogs, cates=cates, categories=categories,
                           loves=loves, su=su, flinks=flinks, plans=plans, msg_borders=msg_borders)
 
 
@blog_bp.route('/themes/<string:theme_name>/')
````

**Comment by weijiang1994** [comment]
没有找到模板文件，你看看template目录下面有没有

**Comment by sci2sci** [comment]
![main](https://user-images.githubusercontent.com/109023279/222875936-3f5345a2-6621-43b0-a5b4-64ddbae83b63.jpg)

**Comment by weijiang1994** [comment]
把.flaskenv文件的APP改成scisci

**Comment by sci2sci** [comment]
FLASK_APP=scisci
FLASK_ENV=development

**Comment by sci2sci** [comment]
改了 很奇怪

**Comment by weijiang1994** [comment]
看看你的目录结构

**Comment by sci2sci** [comment]
![s](https://user-images.githubusercontent.com/109023279/222876108-1bf2e757-5e5c-43b9-aa8b-c8a15f3909e9.jpg)

**Comment by sci2sci** [comment]
File "/Users/kxx/PycharmProjects/SciSci/sci/lib/python3.8/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: main/index.html

**Comment by weijiang1994** [comment]
那你指定一下template的路径试一下

**Comment by sci2sci** [comment]
jinja2.exceptions.TemplateNotFound: /Users/xx/PycharmProjects/SciSci/scisci/templates/main/index.html

**Comment by sci2sci** [comment]
一样的问题啊

**Comment by sci2sci** [comment]
我刚才把文件名所有的blogin代替成scisci就上面问题消失啦。但是又有问题
KeyError
KeyError: 'scisci_BLOG_PER_PAGE'

我估计这哪里设置一下

**Comment by sci2sci** [comment]
难道这个scisci必须大写吗

**Comment by sci2sci** [comment]
urrent_app.config <Config {'ENV': 'development', 'DEBUG': True, 'TESTING': False, 'PROPAGATE_EXCEPTIONS': None, 'PRESERVE_CONTEXT_ON_EXCEPTION': None, 'SECRET_KEY': 'xx', 'PERMANENT_SESSION_LIFETIME': datetime.timedelta(days=31), 'USE_X_SENDFILE': False, 'SERVER_NAME': None, 'APPLICATION_ROOT': '/', 'SESSION_COOKIE_NAME': 'session', 'SESSION_COOKIE_DOMAIN': None, 'SESSION_COOKIE_PATH': None, 'SESSION_COOKIE_HTTPONLY': True, 'SESSION_COOKIE_SECURE': False, 'SESSION_COOKIE_SAMESITE': None, 'SESSION_REFRESH_EACH_REQUEST': True, 'MAX_CONTENT_LENGTH': None, 'SEND_FILE_MAX_AGE_DEFAULT': datetime.timedelta(seconds=43200), 'TRAP_BAD_REQUEST_ERRORS': None, 'TRAP_HTTP_EXCEPTIONS': False, 'EXPLAIN_TEMPLATE_LOADING': False, 'PREFERRED_URL_SCHEME': 'http', 'JSON_AS_ASCII': False, 'JSON_SORT_KEYS': True, 'JSONIFY_PRETTYPRINT_REGULAR': False, 'JSONIFY_MIMETYPE': 'application/json', 'TEMPLATES_AUTO_RELOAD': None, 'MAX_COOKIE_SIZE': 4093, 'AVATARS_SAVE_PATH': '/Users/ketian/PycharmProjects/SciSci/uploads/avatars/', 'BAIDU_TRANS_APPID': 'xx', 'BAIDU_TRANS_KEY': 'xx', 'BLOG_THEMES': {'light': 'light', 'dark': 'dark'}, 'CKEDITOR_CODE_THEME': 'docco', 'CKEDITOR_ENABLE_CODESNIPPET': True, 'CKEDITOR_FILE_UPLOADER': 'be_blog_bp.upload', 'CKEDITOR_HEIGHT': 500, 'CKEDITOR_SERVE_LOCAL': True, 'DATABASE_PWD': '1984Tk!9', 'DATABASE_USER': 'root', 'EXPIRE_TIME': 600, 'LOGIN_LOG_PER_PAGE': 20, 'MAIL_DEFAULT_SENDER': ('scisci Admin', '285662034@qq.com'), 'MAIL_PASSWORD': 'qfngiwdudfvwbjfe', 'MAIL_PORT': 465, 'MAIL_SERVER': 'smtp.qq.com', 'MAIL_USERNAME': '285662034@qq.com', 'MAIL_USE_SSL': True, 'PHOTO_NEED_RESIZE': 1048576, 'REDIS_URL': 'redis://localhost', 'SCHEDULER_API_ENABLED': True, 'SCISCI_BLOG_PER_PAGE': 8, 'SQLALCHEMY_DATABASE_URI': 'mysql+pymysql://root:1984Tk!9@127.0.0.1/blog?charset=utf8mb4', 'SQLALCHEMY_ECHO': False, 'SQLALCHEMY_TRACK_MODIFICATIONS': False, 'WHOOSHEE_MIN_STRING_LEN': 1, 'SQLALCHEMY_BINDS': None, 'SQLALCHEMY_NATIVE_UNICODE': None, 'SQLALCHEMY_RECORD_QUERIES': None, 'SQLALCHEMY_POOL_SIZE': None, 'SQLALCHEMY_POOL_TIMEOUT': None, 'SQLALCHEMY_POOL_RECYCLE': None, 'SQLALCHEMY_MAX_OVERFLOW': None, 'SQLALCHEMY_COMMIT_ON_TEARDOWN': False, 'SQLALCHEMY_ENGINE_OPTIONS': {}, 'BOOTSTRAP_USE_MINIFIED': True, 'BOOTSTRAP_CDN_FORCE_SSL': False, 'BOOTSTRAP_QUERYSTRING_REVVING': True, 'BOOTSTRAP_SERVE_LOCAL': False, 'BOOTSTRAP_LOCAL_SUBDOMAIN': None, 'CKEDITOR_PKG_TYPE': 'standard', 'CKEDITOR_LANGUAGE': '', 'CKEDITOR_WIDTH': 0, 'CKEDITOR_FILE_BROWSER': '', 'CKEDITOR_UPLOAD_ERROR_MESSAGE': 'Upload failed.', 'CKEDITOR_EXTRA_PLUGINS': [], 'CKEDITOR_ENABLE_CSRF': False, 'SHARE_SITES': 'weibo, wechat, douban, facebook,         twitter, google, linkedin, qq, qzone', 'SHARE_MOBILE_SITES': 'weibo, douban, qq, qzone', 'SHARE_HIDE_ON_MOBILE': False, 'SHARE_SERVE_LOCAL': False, 'AVATARS_GRAVATAR_DEFAULT': 'identicon', 'AVATARS_SERVE_LOCAL': False, 'AVATARS_SIZE_TUPLE': (30, 60, 150), 'AVATARS_IDENTICON_COLS': 7, 'AVATARS_IDENTICON_ROWS': 7, 'AVATARS_IDENTICON_BG': None, 'AVATARS_CROP_BASE_WIDTH': 500, 'AVATARS_CROP_INIT_POS': (0, 0), 'AVATARS_CROP_INIT_SIZE': None, 'AVATARS_CROP_PREVIEW_SIZE': None, 'AVATARS_CROP_MIN_SIZE': None}>

**Comment by sci2sci** [comment]
上面没有那些设置scisci_BLOG_PER_PAGE = 8
    scisci_COMMENT_PER_PAGE = 10
    scisci_PHOTO_PER_PAGE = 12

我把那个scisci改成大写就可以。

为啥会发生这种情况 一大写就OK啊。

**Comment by sci2sci** [comment]
为啥 说不能提交包含空的表单!

我看你的default就可以啊
