### ISSUE TITLE
博客继续阅读 按钮

### ISSUE THREAD

**Issue by sci2sci** [weijiang1994/Blogin#31]

**Comment by sci2sci** [comment]
我想设计一个博客文章只显示简介 或者部分。后面遮盖，然后需要继续阅读按钮 如果点击继续阅读按钮现实后请先登录或者注册 这个怎么实现啊。

**Comment by weijiang1994** [comment]
自己思考一下。

**Comment by sci2sci** [comment]
好吧 能否提示参考代码吗

**Comment by weijiang1994** [comment]
有两种实现方式
1. 在前端隐藏博客内容，可以将显示博客内容的div盒子高度设置为固定，然后关闭overflow-y，当用户点击继续阅读的时候，可以先判断是否登录，如果登录了，则显示没有登录则跳转到登录页面，不过这种方式懂前端的人很容易破解；
2. 在后端做限制，当用户未登录的时候，只返回一部分内容，但是由于博客内容是保存的HTML文本，因此需要考虑到截取的时破坏HTML标签的问题；
