### ISSUE TITLE
大佬，请问这是什么原因啊

### ISSUE THREAD

**Issue by unDie-BestHYJ** [weijiang1994/Blogin#36]
![image](https://github.com/weijiang1994/Blogin/assets/110709997/6cf1b289-e26d-4f79-83aa-d06a0d55324b)
![image](https://github.com/weijiang1994/Blogin/assets/110709997/f743ee90-a5a4-44e0-896e-1bf9985c0d4d)

**Comment by unDie-BestHYJ** [comment]
大佬，上面这个问题解决了，但是为什么后端进不去啊
![image](https://github.com/weijiang1994/Blogin/assets/110709997/e906f785-1435-433e-9997-71dfed6b7a70)

**Comment by weijiang1994** [comment]
/backend/admin/index/ 是这个链接

**Comment by unDie-BestHYJ** [comment]
还是不行诶
![image](https://github.com/weijiang1994/Blogin/assets/110709997/5b363229-04f1-46db-aecd-6022f302720b)

**Comment by weijiang1994** [comment]
把你登录用户的role_id 改为1 在数据库手动改

**Comment by unDie-BestHYJ** [comment]
大佬，请问这里怎么一直刷新不出来啊
![image](https://github.com/weijiang1994/Blogin/assets/110709997/dec670ae-c40b-4e4e-8054-b721a05e7c93)

**Comment by unDie-BestHYJ** [comment]
![image](https://github.com/weijiang1994/Blogin/assets/110709997/978eb8dc-b5a7-4598-b7cb-b25f0c2039a8)

**Comment by weijiang1994** [comment]
应该是你的网络问题

**Comment by natsume37** [comment]
<img width="1120" alt="image" src="https://github.com/weijiang1994/Blogin/assets/103176271/edcd4f1a-f8ff-4ec5-ab04-7176ac5dea46">
()[https://natsume-1316988601.cos.ap-chengdu.myqcloud.com/image_own/082314%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE%202023-08-23%20145024e7cc598d52.png]
佬   为什么我已经修改完、但是这个主页haishi还是404呀
