### ISSUE TITLE
个人博客云端部署问题

### ISSUE THREAD

**Issue by unDie-BestHYJ** [weijiang1994/Blogin#37]
大佬，为什么我把博客部署到腾讯云服务器(windows系统)，输入flask run运行之后，我再本地访问不到页面啊
![image](https://github.com/weijiang1994/Blogin/assets/110709997/e85e710c-3dfd-4ab6-93ab-a13682ed8c7f)
![image](https://github.com/weijiang1994/Blogin/assets/110709997/3bb6c531-6fcc-44e8-9b76-cd4f1ae9ff2d)

**Comment by weijiang1994** [comment]
flask run --host 0.0.0.0 @unDie-BestHYJ
