### ISSUE TITLE
AttributeError: 'Babel' object has no attribute 'localeselector'

### ISSUE THREAD

**Issue by unDie-BestHYJ** [weijiang1994/Blogin#38]
大佬，请问这个报错怎么解决啊
![image](https://github.com/weijiang1994/Blogin/assets/110709997/709599b4-969f-4074-b30b-59c0ac1f58b9)

**Comment by unDie-BestHYJ** [comment]
还是不行
![image](https://github.com/weijiang1994/Blogin/assets/110709997/075e7cfb-52a6-4b34-be58-4143a3b4afea)
![image](https://github.com/weijiang1994/Blogin/assets/110709997/4c37e3c5-a89e-41d8-8d81-30f80c30330c)

**Comment by weijiang1994** [comment]
pip install flask-babel==2.0.0

**Comment by unDie-BestHYJ** [comment]
后面又是这个报错
![image](https://github.com/weijiang1994/Blogin/assets/110709997/edbb0485-05bb-4f4c-b964-523160cf852b)

**Comment by weijiang1994** [comment]
你的版本安装的不对吧 pip install itsdangerous==1.1.0
