### ISSUE TITLE
进首页显示404

### ISSUE THREAD

**Issue by unDie-BestHYJ** [weijiang1994/Blogin#39]
请问我把博客部署到ubuntu系统的服务器后，进入首页显示404，但是其它页面正常显示是什么问题啊
![image](https://github.com/weijiang1994/Blogin/assets/110709997/0552de87-77d0-4cd7-b80e-6295eca64d30)
![image](https://github.com/weijiang1994/Blogin/assets/110709997/2f8af7f1-922a-449d-be00-d80fc74656b9)
![image](https://github.com/weijiang1994/Blogin/assets/110709997/9533c8e2-5fce-4bd1-b5a2-ad226ef10829)

**Comment by weijiang1994** [comment]
看看日志，报错了

**Comment by unDie-BestHYJ** [comment]
提示的这个
![image](https://github.com/weijiang1994/Blogin/assets/110709997/efab9d53-c5e5-4474-b5fc-80253da5b96e)

**Comment by unDie-BestHYJ** [comment]
这会不会和python版本有关系啊，我本地用的python3.6就没问题，我云服务器用的Python3.8的，就有这个问题

**Comment by weijiang1994** [comment]
你依赖怎么安装的？是不是pip install -r requirment.txt这个命令？依赖库的版本需要保持一致

**Comment by weijiang1994** [comment]
你看根目录的requirements.txt文件，里面有每个依赖的版本号。

**Comment by unDie-BestHYJ** [comment]
我刚看了，我好像flaalembic==1.4.3没安装，但是这个好像装不了
![image](https://github.com/weijiang1994/Blogin/assets/110709997/a94ac8e1-4291-4ab1-a384-188f33e91140)

**Comment by weijiang1994** [comment]
pip install Flask-SQLAlchemy==2.4.4 SQLAlchemy==1.3.19

**Comment by unDie-BestHYJ** [comment]
zhuangle装了之后又是这个报错
![image](https://github.com/weijiang1994/Blogin/assets/110709997/6f3d5ae4-0fa0-4e7a-953b-71dddd39cfe8)

**Comment by weijiang1994** [comment]
你直接重新安装吧 `pip install -r requirements.txt -i https://pypi.douban.com/simple`

**Comment by weijiang1994** [comment]
没有的库，在requirements.txt文件中删除掉

**Comment by unDie-BestHYJ** [comment]
嗯呐，谢谢大佬

**Comment by weijiang1994** [comment]
可以帮我点一个 :star2: :smile:

**Comment by unDie-BestHYJ** [comment]
没问题😄
