### ISSUE TITLE
博客地址无法访问了

### ISSUE THREAD

**Issue by natsume37** [weijiang1994/Blogin#41]
佬 很喜欢你的博客、但是今天发现你的博客地址访问不了了。佬千万不要放弃这个项目呀、佬。

**Comment by weijiang1994** [comment]
哈哈哈 没放弃呢 只是没啥时间更新 地址还是可以正常打开的~ [https://2dogz.cn/](https://2dogz.cn/)

**Comment by weijiang1994** [comment]
> <img alt="image" width="1120" src="https://user-images.githubusercontent.com/103176271/262366852-d43a81ed-94bb-4cc8-b546-15199d53a170.png"> 佬 你看
这个是你访问频率太高了，触发了一个监控封禁了哈哈哈 我把你IP删掉

**Comment by weijiang1994** [comment]
@natsume37 重试一下 应该可以了

**Comment by natsume37** [comment]
哈哈 好的 
误会了  最近想写个和你一样的博客、想直接用你的开源代码由于技术不行、部署不成功、只能每次看看你的博客自己去试试做做，菜鸟的下下策。感谢佬。
