### ISSUE TITLE
依赖的文件缺失

### ISSUE THREAD

**Issue by woxinpengpai** [weijiang1994/Blogin#45]
`blogin/templates/backend/base.html`第二行 `{% extends "bootstrap/base.html" %}`用到了bootstrap/base.html, 然而项目中并没有这个文件夹以及文件

**Comment by weijiang1994** [comment]
这个是一个第三方库的里面的文件，不是项目中的模板文件。

**Comment by weijiang1994** [comment]
安装`bootstrap-flask` 和 `flask-bootstrap`这两个库就有了。

**Comment by woxinpengpai** [comment]
> 安装`bootstrap-flask` 和 `flask-bootstrap`这两个库就有了。

好的，我现在试一下
