### ISSUE TITLE
请问有前端的模板吗

### ISSUE THREAD

**Issue by wylnevergiveup** [weijiang1994/Blogin#5]
请问是前后端分离的吗？大佬有前端的模板吗？

**Comment by TelBotDev** [comment]
> 请问是前后端分离的吗？大佬有前端的模板吗？

博主好像是手撸的html模板哎...

**Comment by weijiang1994** [comment]
> 请问是前后端分离的吗？大佬有前端的模板吗？

不是的，通过模板渲染的

**Comment by weijiang1994** [comment]
> > 请问是前后端分离的吗？大佬有前端的模板吗？
> 
> 看了下[这里](https://github.com/weijiang1994/Blogin/tree/master/blogin/templates)，有无数个各种命名规范的html。博主好像是手撸的html模板哎...

是通过模板渲染的，没有前后端分离。这种个人项目没必要，用模板渲染很快。
