### ISSUE TITLE
如有疑惑请使用issue提交，避免使用邮箱提问

### ISSUE THREAD

**Issue by weijiang1994** [weijiang1994/Blogin#6]
你的疑惑可能也是别人的疑惑，使用issue提交，可以极大的方便你、我、他~
## 请尽量避免使用邮箱表达你的疑惑，谢谢啦~

**Comment by T485556595** [comment]
raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'baidu'

报这个错

**Comment by weijiang1994** [comment]
> ```
> raise NoSectionError(section) from None
> ```
> 
> configparser.NoSectionError: No section: 'baidu'
> 
> 报这个错

按照res目录下的config.ini文件将config.example内容复制进去
另外，提交issue麻烦新建issue
