### ISSUE TITLE
这个表是怎么映射的

### ISSUE THREAD

**Issue by T485556595** [weijiang1994/Blogin#9]
![image](https://user-images.githubusercontent.com/84732966/129869507-d310a548-caf0-44f9-915f-b441864e6308.png)

**Comment by weijiang1994** [comment]
> ![image](https://user-images.githubusercontent.com/84732966/129869507-d310a548-caf0-44f9-915f-b441864e6308.png)

报错信息说明这张表在数据库中不存在

**Comment by weijiang1994** [comment]
项目的数据库操作使用的flask-sqlalchemy库的ORM，表模型定义可以看`models.py`文件
